- name: Add docker repository
  block:

    - name: Apt update
      apt:
        update_cache: true

    - name: Install packages to use repo over HTTPS
      apt:
        name: 
        - ca-certificates
        - curl
        - gnupg

    - name: Making keyrings directory
      shell:
        cmd: 'sudo install -m 0755 -d {{keyrings_dir}}'

    - name: Add GPG key
      shell:
        cmd: 'curl -fsSL {{docker_url}}/gpg | sudo gpg --dearmor -o {{keyrings_dir}}/docker.gpg'

    - name: Change mode for docker.gpg
      shell:
        cmd: 'sudo chmod a+r {{keyrings_dir}}/docker.gpg'

    - name: Checking architecture 
      shell:
        cmd: '{{arch}}'
      register: arch_result
 
    - name: Add docker repository
      apt_repository:
        filename: docker
        repo: 'deb [arch={{arch_result.stdout}} signed-by={{keyrings_dir}}/docker.gpg] {{docker_url}} {{ansible_lsb.codename}} stable'

  tags: repo
  become: true
  when: ansible_distribution in ['Debian']
