---

- hosts: all
  become: true
  pre_tasks:

    - name: Update repositories
      tags: always
      apt:
        update_cache: true
      when:
        ansible_distribution in ['Debian']

  roles:
  - base

- hosts: web_servers
  become: true
  roles:
  - web_servers

- hosts: db_servers
  become: true
  roles:
  - db_servers

- hosts: docker_servers
  become: true
  roles:
  - docker_servers
