---

- hosts: all
  become: true
  tasks:

    - name: apt update && install apache, mysql-server
      apt:
        update_cache: true
        name:
          - apache2
          - default-mysql-server
      when:
        ansible_distribution in ['Debian']
