- name: Install apache2
  tags: web
  apt:
    name: apache2
    state: latest
  when: ansible_distribution == 'Debian'

- name: Copying site file
  tags: web
  copy:
    src: ../files/default_site.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
  when: ansible_distribution == 'Debian'
