- name: Debug message
  debug:
    msg: A date on node is {{ ansible_date_time.date }}

- name: Checking uptime
  shell: /usr/bin/uptime
  register: uptime_result

- name: Debug uptime
  debug:
    msg: '{{uptime_result.stdout}}'
